CREATE TABLE IF NOT EXISTS "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"password_hash" text NOT NULL,
	"name" varchar(255),
	"deliveryDay" integer DEFAULT 1 NOT NULL,
	"delivered" boolean DEFAULT false NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"keywords" jsonb NOT NULL,
	"role" varchar(20) DEFAULT 'Other' NOT NULL,
	"stripe_customer_id" text,
	"stripe_subscription_id" text,
	"stripe_product_id" text,
	"plan" varchar(50) DEFAULT 'free' NOT NULL,
	"note" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"active_notes" jsonb DEFAULT '[]'::jsonb NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email"),
	CONSTRAINT "users_stripe_customer_id_unique" UNIQUE("stripe_customer_id"),
	CONSTRAINT "users_stripe_subscription_id_unique" UNIQUE("stripe_subscription_id")
);
